import { User } from 'app/models/admin/user';
import { Branches } from 'app/models/admin/branches';
import { IncompleteAccountBranch } from '../incomplete-document-account/model/incomplete-account-branch';
import { AbnormalBalanceBranch } from './abnormal-balance/abnormal-balance-branch';
import { AssetLiabilityBranch } from './asset-liability/asset-liability-branch';
import { AtmCardBranch } from './atm_card/atm-card-branch';
import { CashPerformanceBranch } from './cash_performance/cash-performance-branch';
import { ChangeTrackerBranchAudit } from './change-tracker-branch-audit';
import { DormantInactive } from './dormant/dormant-inactive';
import { NegotiableInstrument } from './negotiable_instrument/negotiable-instrument';
import { OperationalDescripancyBranch } from './operational-descripancy/operational-descripancy-branch';
import { Statusofaudit } from './statusofaudit';
import { CashCount } from './cash-count';
import { SuspenseAccount } from './suspense_account/suspense-account';
import { ControllableExpense } from './ControllableExpense/controllable-expense';
import { CashManagementBranch } from './Cash_Management_Branch/cash-management-branch';
import { LoanAndAdvance } from './loanAndAdvance/loan-and-advance';
import { OverDraft } from './overdraft/over-draft';
import { MemorandumContigent } from './memorandum/memorandum-contigent';
import { LongOutstandingItem } from './long_outstanding_item/long-outstanding-item';


export class BranchFinancialAudit {
  id?: number;
  case_number?: String;
  branch_manager?: User;
  auditor?: User;
  reviewer?: User;
  followup_officer?: User;
  approver?: User;
  auditee?: User;
  finding_date?: String;
  finding?: String;
  finding_detail?: String;
  impact?: String;
  recommendation?: String;
  observation?: String;
  review_status?: number;
  approve_status?: number;
  rectification_date?: String;
  rectification_status?: number;
  save_template?: Boolean;
  edit_auditee?: Boolean;
  status: number;
  passed_date?: String;
  drafted_date: String;
  response_added?: Number;
  division_assigned?: Number;
  is_edited?: Boolean;
  editor?: User;
  change_tracker_branch_audit: ChangeTrackerBranchAudit[];
  category?: string;
  audit_date?: String;
  approved_date?: String;
  reviewed_date?: String;
  responded_date?: String;
  finding_status?: String;
  auditor_status?: Number;
  branch_id?: Number;
  auditor_id?: Number;
  approver_id?: Number;
  reviewer_id?: Number;
  abnormalBalanceBranch?: AbnormalBalanceBranch = {};
  assetLiabilityBranch?: AssetLiabilityBranch = {};
  branch?: Branches = {};
  incompleteAccountBranch?: IncompleteAccountBranch = {};
  cashPerformanceBranch?: CashPerformanceBranch = {};
  atmCardBranch?: AtmCardBranch = {};
  operationalDescripancyBranch?: OperationalDescripancyBranch = {};
  file_urls?: String[];
  statusofAudit?: Statusofaudit = {};
  file_flag?: boolean;
  action_plan?: String;
  dormantInactive?: DormantInactive = {};
  bmFileUrls?: String[];
  memorandumContigent?: MemorandumContigent = {};
  cashManagementBranch?: CashManagementBranch = {};
  loanAndAdvance?: LoanAndAdvance = {};
  //overDraft?:OverDraft = {};
  controllableExpense?: ControllableExpense = {};
  cashcount?: CashCount = {};
  negotiableInstrument?: NegotiableInstrument = {};
  suspenseAccountBranch?: SuspenseAccount = {};
  regional_compiler_status?: number;
	regional_compiler_compiled_date?: String;
	regional_compiler_submitted?: number ;
	regional_compiler_submitted_date?: String;
	division_compiler_id?: Number;
	division_compiler_review_status?: number;
	division_compiler_reviewed_date?: String;
	division_compiler_status?: number ;
	division_compiler_compiled_date?: String;
	division_compiler_submitted?: number;
	division_compiler_submitted_date?: String;
	approver_edited_date?: String;
  audit_type?:String;
  reciever?: User;
  audit_finding?: String;
  audit_impact?: String;
  audit_recommendation?: String;
  branch_name?:String;
  audit_case_number?:String;
  long_outstanding?: LongOutstandingItem = {};
  outstanding_date?: number;
  unseen_remark?: number;
  ing?: String;
}
